create schema `JBMessenger-User`;
use `JBMessenger-User`;

CREATE TABLE USERS(
	EMAIL VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	MOB_NO VARCHAR(10) NOT NULL UNIQUE,
	PASSWORD VARCHAR(30) NOT NULL
);

INSERT INTO USERS (EMAIL,NAME,MOB_NO,PASSWORD) VALUES ('jimbrown@gmail.com','JIMBROWN','8129254371','jim1234');
INSERT INTO USERS (EMAIL,NAME,MOB_NO,PASSWORD) VALUES ('shino@gmail.com','SHINO','7012334137','shino1234');
INSERT INTO USERS (EMAIL,NAME,MOB_NO,PASSWORD) VALUES ('amal@gmail.com','AMAL','7558859903','amal1234');